/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutPage: typeof import('./src/components/AboutPage.vue')['default']
    AddNewProperty: typeof import('./src/components/AddNewProperty.vue')['default']
    AdminDashboard: typeof import('./src/components/adminDashboard.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
    GoogleMap: typeof import('./src/components/GoogleMap.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    LoginV2: typeof import('./src/components/LoginV2.vue')['default']
    Map: typeof import('./src/components/Map.vue')['default']
    Messages: typeof import('./src/components/Messages.vue')['default']
    PrivacyPolicy: typeof import('./src/components/PrivacyPolicy.vue')['default']
    Profile: typeof import('./src/components/Profile.vue')['default']
    Properties: typeof import('./src/components/Properties.vue')['default']
    PropertyCard: typeof import('./src/components/PropertyCard.vue')['default']
    PropertyDetails: typeof import('./src/components/PropertyDetails.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SavedProperties: typeof import('./src/components/SavedProperties.vue')['default']
    Settings: typeof import('./src/components/Settings.vue')['default']
    Signup: typeof import('./src/components/Signup.vue')['default']
    SignupV2: typeof import('./src/components/SignupV2.vue')['default']
    TermsAndCondition: typeof import('./src/components/TermsAndCondition.vue')['default']
  }
}
