/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddNewProperty: typeof import('./src/components/AddNewProperty.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    copy: typeof import('./src/components/SavedProperties copy.vue')['default']
    CreateNewProperty: typeof import('./src/components/CreateNewProperty.vue')['default']
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Messages: typeof import('./src/components/Messages.vue')['default']
    Properties: typeof import('./src/components/Properties.vue')['default']
    PropertyCard: typeof import('./src/components/PropertyCard.vue')['default']
    PropertyDetails: typeof import('./src/components/PropertyDetails.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SavedProperties: typeof import('./src/components/SavedProperties.vue')['default']
    Settings: typeof import('./src/components/Settings.vue')['default']
    Signup: typeof import('./src/components/Signup.vue')['default']
  }
}
